In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# here we are working on Tensorflow version 2.1.0 so we need to write tensorflow.keras.
#keras is in built function in Tensorflow.
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, Input, Dropout,Flatten, Conv2D
from tensorflow.keras.layers import BatchNormalization, Activation, MaxPooling2D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.utils import plot_model
from IPython.display import SVG, Image

In [ ]:
train_location = "/content/drive/MyDrive/SCA/dataset"
test_location = "/content/drive/MyDrive/SCA/dataset"
filepath = '/content/drive/MyDrive/SCA/model/Sickle_VGG16_model_M1.h5'

In [ ]:
from tensorflow.keras.models import load_model
Detection=load_model(filepath)

In [ ]:
img_size=224
batch_size=3
num_class=3

In [ ]:
# Complete Dataset images can be loaded using ImageDataGenerator function

datagen_train=ImageDataGenerator(horizontal_flip=True)
train_generator=datagen_train.flow_from_directory(train_location,target_size=(img_size,img_size),batch_size=batch_size,class_mode='categorical',shuffle=True)

datagen_test=ImageDataGenerator(horizontal_flip=True)
validation_generator=datagen_test.flow_from_directory(test_location,target_size=(img_size,img_size),batch_size=batch_size,class_mode='categorical',shuffle=True)


Found 746 images belonging to 3 classes.
Found 746 images belonging to 3 classes.


In [ ]:
classes=train_generator.class_indices
classes

{'Sickle-ISC': 0, 'normal rbc': 1, 'thaleesmia': 2}

In [ ]:
category=[]
for i in classes:
          category.append(i)

category

['Sickle-ISC', 'normal rbc', 'thaleesmia']

In [ ]:
from skimage import io
import os
from tensorflow.keras.preprocessing import image

image_directory=test_location
dataset = []
predict_result=[]
label =[]


my_folders = os.listdir(image_directory)
for i, folder_name in enumerate(my_folders):
    #print(str(i)+': ' +folder_name)

    loc=0
    for j in category:
      if(j==folder_name):
        lab=loc
      loc+=1
    lab

    my_images = os.listdir(image_directory+'/'+folder_name)
    for j,image_name in enumerate(my_images):
      #print(str(j)+': ' +image_name)

      file_name = image_directory+'/'+folder_name + '/' + image_name

      test_img=image.load_img(file_name,target_size=(img_size,img_size))
      test_img=image.img_to_array(test_img)
      test_img=np.expand_dims(test_img,axis=0)
      result=Detection.predict(test_img)

      label.append(lab)
      predict_result.append(result.argmax())

      print(f'{folder_name} : {str(lab)} , Predicted : {result.argmax()}  ')




1/1 [==============================] - 1s 892ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 505ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 0s 487ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 0s 487ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 510ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 502ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 0s 499ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 698ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 1s/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 982ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 0s 496ms/step
Sickle-ISC : 0 , Predicted : 0  
1/1 [==============================] - 1s 509ms/step
Sick

In [ ]:
correct=0
Wrong=0


for i in range(len(label)):
  if(predict_result[i]==label[i]):
    correct+=1
  else:
    Wrong+=1

print(f'correct: {correct} , Wrong: {Wrong}')




correct: 709 , Wrong: 38


In [ ]:
Acc= correct/(correct+Wrong)
Acc*100

94.91298527443107

In [ ]:

y_test = label
y_pred = predict_result

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report
from sklearn import metrics

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('Test set accuracy: ',metrics.accuracy_score(y_test, y_pred))

[[ 62   0   2]
 [  0 339   0]
 [  0   2 278]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        64
           1       0.99      1.00      1.00       339
           2       0.99      0.99      0.99       280

    accuracy                           0.99       683
   macro avg       1.00      0.99      0.99       683
weighted avg       0.99      0.99      0.99       683

Test set accuracy:  0.9941434846266471


In [ ]:
confusion = metrics.confusion_matrix(y_test, y_pred)
confusion.ravel()

array([ 62,   0,   2,   0, 339,   0,   0,   2, 278])

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.9941434846266471